version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspaces/${localWorkspaceFolderBasename}:cached
    command: sleep infinity
    network_mode: host
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    network_mode: host
    env_file:
      - .env

volumes:
  mongodb-data:
    name: mongodb-data
